name: namibia_hockey_union
description: Namibia Hockey Union mobile application.
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  realm: ^1.5.0
  flutter_riverpod: ^2.4.9
  go_router: ^12.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  csv: ^6.0.0  # Updated to null-safe version
  path_provider: ^2.1.1
  google_sign_in: ^6.1.5

  realm_dart: any
dev_dependencies:
  build_runner: ^2.4.6
  realm_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/